In [1]:
mi_matriz_numpy = [[1,2,3],[4,5,6],[7,8,9]]

In [2]:
mi_matriz_numpy

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
mat = mi_matriz_numpy

In [4]:
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
import numpy as np

In [6]:
mat*2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mat*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [12]:
mat.ndim

2

In [13]:
mat.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

%time

In [15]:
%time
mat.T

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 11.9 µs

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [16]:
%time
mat.T.T

CPU times: user 4 µs, sys: 1e+03 ns, total: 5 µs
Wall time: 9.06 µs

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
%time
mat.T

CPU times: user 4 µs, sys: 2 µs, total: 6 µs
Wall time: 11 µs

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [18]:
%time
mat.T.T

CPU times: user 4 µs, sys: 1e+03 ns, total: 5 µs
Wall time: 8.82 µs

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
%time
mat.T

CPU times: user 6 µs, sys: 7 µs, total: 13 µs
Wall time: 11 µs

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [31]:
%%time
mat.T

CPU times: user 10 µs, sys: 1 µs, total: 11 µs
Wall time: 16 µs

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
%timeit mat.T

The slowest run took 34.25 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 174 ns per loop

In [40]:
mat.T.mean()

5.0

In [41]:
mat*mat

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

imports pandas as pd

In [4]:
import pandas as pd

In [43]:
serie = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [44]:
serie

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [11]:
mi_df= {'Municipio':["mty","spgg","sta_c","garcia"],"Temp":[35,36,37,38]}

In [2]:
type(mi_df)

dict

In [13]:
df = pd.DataFrame(mi_df)

In [6]:
type(df)

pandas.core.frame.DataFrame

In [14]:
df

  Municipio  Temp
0       mty    35
1      spgg    36
2     sta_c    37
3    garcia    38

In [16]:
df[df['Temp']<37]

  Municipio  Temp
0       mty    35
1      spgg    36

In [30]:
df['Temp']<37

0     True
1     True
2    False
3    False
Name: Temp, dtype: bool

In [31]:
df['Temp']>=36

0    False
1     True
2     True
3     True
Name: Temp, dtype: bool

In [34]:
[df['Temp']<37] and [df['Temp']>=36]

[0    False
 1     True
 2     True
 3     True
 Name: Temp, dtype: bool]

In [35]:
[[df['Temp']<37] and [df['Temp']>=36]]

[[0    False
  1     True
  2     True
  3     True
  Name: Temp, dtype: bool]]

In [38]:
[[df['Temp']>=36] and [df['Temp']<37]]

[[0     True
  1     True
  2    False
  3    False
  Name: Temp, dtype: bool]]

In [41]:
np.mean(df['Temp'])

36.5

In [40]:
import numpy as np

In [42]:
df['Temp'].mean()

36.5

In [44]:
datos = pd.read_csv("https://gist.githubusercontent.com/israelzuniga/de79faf13d5fe48ea4f65c8e04fdca6e/raw/20d024adffba39da848eb3b7f80a958d8eb7d380/train.csv")

In [45]:
datos

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.0,1,0,28134,11.5000,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
870,871,0,3,"Balkic, Mr. Cerin",male,26.0,0,0,349248,7.8958,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [46]:
"visualizacion"

'visualizacion'

In [48]:
import matplotlib as plt
%matplotlib nbagg

In [50]:
datos.Age.hist()